### ISSUE TITLE
Process without elevation

### ISSUE THREAD

**Issue by akudrya** [mapbox/togeojson#100]
Hi @tmcw, awesome tool in general!

Do you have any different versions of the utility?
Basically I'm looking for a version where no elevation is specified. 

Where can I find it? 

Thanks a lot!

**Comment by tmcw** [comment]
Hi Alex!

There isn't a version of toGeoJSON without elevation parsing, but if that's something you need, you can write a quick script that removes elevation from any GeoJSON file by using the `@turf/meta` module: here's an example: https://gist.github.com/tmcw/3d521e869976f4c53f72d83726d2b4f8

Hope that helps,

- Tom

**Comment by akudrya** [comment]
@tmcw thanks for the heads up!
