### ISSUE TITLE
Don't recommend jsdom in the README

### ISSUE THREAD

**Issue by danvk** [mapbox/togeojson#104]
I just ran into #4.

While the `togeojson` executable uses `xmldom`, the README [still recommends][1] using `jsdom`.

[1]: https://github.com/mapbox/togeojson/tree/46e3cafd346a203814900882b98c087d6df31bd7#nodejs

**Comment by tmcw** [comment]
Good catch, can you roll a PR implementing this change?

**Comment by danvk** [comment]
Sure, done.
