### ISSUE TITLE
Any way to group same named polygons as multipolygons?

### ISSUE THREAD

**Issue by jeremytregunna** [mapbox/togeojson#106]
I'm looking for a way to take my KML data, which contains baths that are part of the same object which don't connect, and instead of producing 12 or 26 or however many it is for any arbitrary object, produce a set of independent polygons, rather, to produce one multipolygon. Is there a way to do this with togeojson?

**Comment by tmcw** [comment]
Hi Jeremy,

This isn't something that toGeoJSON will do for you directly, since it converts from KML to the most verbatim GeoJSON representation possible. But once you're in GeoJSON, you can use JavaScript to do this. Here's some code - untested, just a sketch of the direction you could take.

```js
var featureCollection = toGeoJSON(kml);

var groupedFeatures = {
  type: 'Feature',
  properties: featureCollection.features[0].properties,
  geometry: {
    type: 'MultiPolygon',
    coordinates: featureCollection.features.map(function (feature) {
      return feature.geometry.coordinates;
    })
  }
};
```

**Comment by jeremytregunna** [comment]
Yeah I wrote a ruby script which does the same thing basically, just wondering if there was a native way to do it. Thanks.
