### ISSUE TITLE
NaN coordinates for LinearRing in IE 10 and 11

### ISSUE THREAD

**Issue by skinnyjames** [mapbox/togeojson#112]
Thanks for the great library!

I'm having issues converting kml data to geojson in IE 10 and 11.        
```
     jQuery.ajax({
       url: url, 
       dataType: "text", 
       success: function(data){
         xml = jQuery.parseXML(data);
         kmlData = toGeoJSON.kml(xml);
         current = kmlData;
         updatePolygons(kmlData);
     }});
```

I can reference the xml parsed by jQuery and retrieve coordinates, but after converting it to geojson, the coordinates are NaN

![geojson](https://cloud.githubusercontent.com/assets/795902/19573214/e6e10732-96ca-11e6-8f81-982de42dc04b.png)

This is what it looks like in Chrome.

![geojson-chrome](https://cloud.githubusercontent.com/assets/795902/19573265/3a742960-96cb-11e6-9409-5e2b31cd28ed.png)

I'm sort of at a loss, I'm pretty sure the xml data is correct.  Any ideas?

**Comment by tmcw** [comment]
There are, unfortunately, many many IE bugs, even in IE10 and 11. This is likely one of them. I don't have a good testing setup for the IEs, so if you want to console.log the DOM and see if, for instance, the coordinate nodes are correct, or adding breakpoints to toGeoJSON to identify the problem area, please do so.

**Comment by skinnyjames** [comment]
Sounds good!  I'll try to identify what's going on.

**Comment by skinnyjames** [comment]
This was resolved using the newest release.
