### ISSUE TITLE
Invalid string length

### ISSUE THREAD

**Issue by Ciwan1859** [mapbox/togeojson#115]
Hello

I tried converting a KML file to GeoJSON but I got the [following error](http://imgur.com/a/O9wXR)!

I'm on a windows machine using the latest version of node.

The KML I'm trying to convert [is this](http://geoportal.statistics.gov.uk/datasets/c4a62d87de9f4b6087cf5f1515d5a0c1_0). Any help would be greatly appreciated.

Thank you.

**Comment by tmcw** [comment]
Hi,

Thanks for the detailed error report. This KML file is 65 megabytes, so it's 68,588,287 characters long and converts into an even larger GeoJSON file. That's hitting a [built-in limit in the V8 JavaScript engine](https://github.com/nodejs/node-v0.x-archive/issues/14170).

Unfortunately, this is out of scope for toGeoJSON: huge files are not part of the problem we're trying to solve, and would open up cans of worms that'd make toGeoJSON less stable and simple for small files. I'd recommend using ogr2ogr instead for this example.

- Tom

**Comment by Ciwan1859** [comment]
No probs, thanks Tom.
