### ISSUE TITLE
KML GroundOverlays support?

### ISSUE THREAD

**Issue by simopaasisalo** [mapbox/togeojson#118]
Hi,

Are there any plans for implementing support for KML GroundOverlays?

**Comment by tmcw** [comment]
Hey Simo,

Although it's something that I certainly want to be supported, I don't think that functionality really belongs in toGeoJSON.

The reasoning is that this module supports converting all KML features that have commonplace equivalents in GeoJSON. GroundOverlay, like [folder](https://github.com/mapbox/togeojson/issues/64) is a KML feature with no commonplace equivalent in GeoJSON. We could invent our own encoding just to get either through - some property that refers to the folder, or some polygon encoding that roughly encodes to a GroundOverlay - but support for those new, specific kinds of GeoJSON would be lackluster, causing downstream users to wonder why they have solid polygons where there should be images.

So, I definitely encourage you to dig into this issue - starting with a fork of toGeoJSON might get the job done faster.  But, while this is an important issue, implementing it would change the scope of toGeoJSON and I'd like to keep the scope-as-is.

- Tom

**Comment by simopaasisalo** [comment]
Hey Tom,

Thanks a lot for the answer, and the reasoning is totally acceptable.
Could you maybe add this information to the ReadMe, like the NetworkLinks section?
