### ISSUE TITLE
Performance in browser really sucks

### ISSUE THREAD

**Issue by andischan** [mapbox/togeojson#120]
I have an 800 KB GPX file, which freezes my Chromium when trying to convert it online.

**Comment by tmcw** [comment]
Indeed! Use ogr2ogr: toGeoJSON is not intended for gigantic files.

**Comment by mourner** [comment]
800 KB is quite small by today's browser standards though — I wouldn't call that gigantic. 

@andischan does it happen only on that file or any GPX files of similar size? Does it "freeze" withouht recover, or just completes in am absurdly long time? How do the other browsers like Firefox or Safari behave? Can you try running the Chrome DevTools profiler when the conversion happens and then share the results?
