### ISSUE TITLE
Uncaught TypeError: x.getElementsByTagName is not a function

### ISSUE THREAD

**Issue by fullhdpixel** [mapbox/togeojson#122]
Following piece of code returns: Uncaught TypeError: x.getElementsByTagName is not a function
    at get (togeojson.js:15)
    at Object.kml (togeojson.js:110)
    at <anonymous>:1:11

`toGeoJSON.gpx('<?xml version="1.0" encoding="UTF-8" standalone="no" ?><gpx xmlns="http://www.topografix.com/GPX/1/1" creator="MyRoutes.io" version="1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd"><trk><name>MyRoutes 5km goor (5.01 km).gpx</name><trkseg><trkpt lat="52.22547" lon="6.6368"><time>2017-04-09T13:04:00Z</time></trkpt><trkpt lat="52.22598" lon="6.63798"><time>2017-04-09T13:04:00Z</time></trkpt><trkpt lat="52.22598" lon="6.63798"><time>2017-04-09T13:04:00Z</time></trkpt><trkpt lat="52.22418" lon="6.64129"><time>2017-04-09T13:04:00Z</time></trkpt><trkpt lat="52.22418" lon="6.64129"><time>2017-04-09T13:04:00Z</time></trkpt><trkpt lat="52.22547" lon="6.6368"><time>2017-04-09T13:04:00Z</time></trkpt></trkseg></trk></gpx>')`

**Comment by fullhdpixel** [comment]
Would've been nice if the documentation showed how this is done:

`var geojson = toGeoJSON.gpx((new DOMParser()).parseFromString(gpxdata, 'text/xml'))`

**Comment by bhousel** [comment]
Sorry about that @fullhdpixel..  The README [does make mention of this](https://github.com/mapbox/togeojson#protips) but if you want to suggest some changes that might make it clearer and save people's time, I'd be happy to update our documentation.
