### ISSUE TITLE
Indicate folder location in returned object

### ISSUE THREAD

**Issue by wayofthefuture** [mapbox/togeojson#127]
So we have a large KML file divided into different folders. These layers are styled differently via GeoJSON so we need to find of way of indicating which folder the feature is in.

Currently, it looks like it returns a flat array of objects, which makes sense because that's the GeoJSON standard. Any thoughts about maybe adding a properties item to each feature which could indicate the parent folder name?

If possible maybe pass an options object to the function to enable the adding of folder names inside of the properties?

tj.kml(kml, {indicateFolders: true});

**Comment by wayofthefuture** [comment]
Found a better way... closed

**Comment by xavieramoros** [comment]
@wayofthefuture I would love to hear what is the better way. 

I have exactly the same problem, a big KML with a folder structure. Thanks!

**Comment by wayofthefuture** [comment]
Using xml2js the folder structure is retained... you have to manually parse the returned object and set the folder location property manually in the geoJson. It's harder but it works.

**Comment by xavieramoros** [comment]
That makes sense, thanks! 
I finally decided to use @FBrusquetti solution as seen in #64 , just add the folder info to the toGeoJSON returned:
https://github.com/FBrusquetti/togeojson/commit/4219d384d80cbf4b7fe743c482e0ac54990f5bef
