### ISSUE TITLE
Unbalanced properties array length

### ISSUE THREAD

**Issue by sehaas** [mapbox/togeojson#128]
My GPSr[0] sometimes produces GPX files with one or more `trkpt` without an heart rate value.
Loading these GPX files with togeojson lead to unbalanced properties arrays.
I have uploaded a sample to this gist: [missing_hr example](https://gist.github.com/sehaas/11e17939e20ba0d29b57de6856bb22f6
).
It contains 10 trackpoints, where `trkpt` six has no HR value. The resulting geojson properties contain arrays with 10 `coordTimes` but only 9 `heartRates`.
So the heartRates array gets shifted left for every missing value.

Writing `null` values for missing data would keep the array length the same.

[0] Garmin Oregon 600 with NC-17 HR4 monitor connected via ANT+

**Comment by bhousel** [comment]
Done in #129 - thanks @sehaas 👍
