### ISSUE TITLE
kml to geojson conversion changes float types to string types

### ISSUE THREAD

**Issue by tdinetta7** [mapbox/togeojson#131]
running `togeojson single_kml.kml > single_kml.geojson`  
In my KML I have a value explicitly defined as a float: 
```
<SimpleData name="normalized_color" xmlns:py="http://codespeak.net/lxml/objectify/pytype" py:pytype="float">24.110576923076923</SimpleData>
 ```   
The resultant geojson ends up turning this value into a string (noted by the quote marks): `"normalized_color": "24.110576923076923"`  
  
This is very problematic as I am trying to use this value with my custom mapbox Style's Property Function to color the Polygons I am importing.  Because it is a string i cannot use any of the data range calculations provided by mapbox to color my shapes.  

[single_kml.txt](https://github.com/mapbox/togeojson/files/1333344/single_kml.txt)

**Comment by tmcw** [comment]
pytype is a python convention that is not part of the KML spec - toGeoJSON shouldn't have any special handling for this kind of input. If, eventually, the [Schema element](https://developers.google.com/kml/documentation/kmlreference#schema) is implemented, then it would have support for typed SimpleData fields, but for now everything is strings. The workaround is writing a little JavaScript, Python, or any other language to parse the numbers-in-strings into numbers.
