### ISSUE TITLE
kml to geojson creates illegal GeometryCollection inside a FeatureCollection

### ISSUE THREAD

**Issue by samsammurphy** [mapbox/togeojson#135]
I would like to add a new vector dataset in mapbox generated from Google Earth Engine (GEE) polygons.

I was having trouble importing the 'old' style geojson (produced by GEE) into mapbox, so tried converting the GEE kml files to a mapbox-friendly file using togeojson.

The issue I am having is that any MultiGeometry in the kml is converted to an illegal FeatureCollection (i.e. one that contains a GeometryCollection) in the output geojson, for example: [vectors.zip](https://github.com/mapbox/togeojson/files/1599867/vectors.zip).

A [similar issue](https://github.com/mapbox/mapbox-gl-js/issues/2778) was posted in mapbox-gl-js and they suggested using [geojsonhint](https://github.com/mapbox/geojsonhint) to catch these sorts of errors. This is the message I got when running geojsonhint with the geojson.json file inside vectors.zip:

      7860:1  warning  Polygons and MultiPolygons should follow the right-hand rule

It does not catch the GeometryCollection (inside a Feature Collection) error.

Tips, advice, help greatly appreciated. 

A mapbox fan.

**Comment by samsammurphy** [comment]
GeometryCollections not supported: https://www.mapbox.com/api-documentation/#the-dataset-object

**Comment by samsammurphy** [comment]
Hi @alexyuly, My reasoning was that because it was a third party tool (Google Earth Engine) that was producing the invalid GeoJSON, it's not really an issue with mapbox.. accept maybe to give a better error message. Re-opening until further notice.

**Comment by alexyuly** [comment]
I wrote a function to transform the GeoJSON returned by `toGeoJSON.kml`, in order to replace each Feature that has a GeometryCollection, with multiple features each with a single Geometry:

```
const normalizeGeojson = (geojson) => {
  if (geojson.type === 'FeatureCollection') {
    return Object.assign(
      {},
      geojson,
      {
        features: geojson.features.reduce(
          (result, each) => result.concat(normalizeGeojson(each)),
          [],
        ),
      }
    )
  }
  if (geojson.type === 'Feature' && geojson.geometry.type === 'GeometryCollection') {
    return geojson.geometry.geometries.map((geometry) => Object.assign(
      {},
      geojson,
      { geometry },
    ))
  }
  return geojson
};
```

Passing my GeoJSON data through this function allowed me to render it using `deck.gl` (which is unaffiliated with MapBox, but it may lead many developers here), whereas without this function, `deck.gl` threw an error that it doesn't support GeometryCollections.

Would it be useful for me to submit a PR with this code?

**Comment by samsammurphy** [comment]
I see your point @alexyuly. There are a couple of solutions that come to mind

1. refuse to convert kml's that contain GeometryCollections. 
2. guess what to convert GeometryCollections into

The first seems both easier and less risky imo. 

@tmcw  Could we get your opinion on best way forward?

**Comment by alexyuly** [comment]
@samsammurphy Ok, I understand. The source KML already has GeometryCollections, so that's the root of the problem, not the GeoJSON conversion process. If that's the case, then I can find a different workaround. I appreciate the update.

**Comment by tmcw** [comment]
You'll need to acquire assistance from someone tasked with maintaining this module; I no longer work at Mapbox/have commit access/maintain any modules in that organization.

**Comment by samsammurphy** [comment]
@alexyuly I missed your last comment (swear it wasn't there before!). Awesome! Yeah a PR would help a whole bunch of people out probably.

**Comment by samsammurphy** [comment]
Thanks @tmcw!

Hello @vincentsarago !! =]     Do you know who we could talk to about this repo?

**Comment by bhousel** [comment]
Hey @samsammurphy I can help get this fix merged.. 

@alexyuly's code to break up the GeometryCollections looks pretty sensible to me at a quick glance, although it uses ES6 features and `Object.assign` which limit its compatibility with older versions of Node and older browsers.  (I'm using this library in a [downstream project](https://github.com/openstreetmap/iD) that still supports IE11).

@alexyuly do you have interest in submitting a PR or would you prefer for me to adapt your code to fix this issue?

**Comment by alexyuly** [comment]
@bhousel 
Thanks for the reply. I'm happy to remove the ES6 features and Object.assign, and submit a PR.

**Comment by tmcw** [comment]
Again, sorry to be the guy who says no, but it would be a bad idea to hobble toGeoJSON to compensate for downstream issues with the features API or Mapbox GL JS.

toGeoJSON's contract is that it produces valid GeoJSON, and GeometryCollections are valid GeoJSON. I wrote [geojson-flatten](https://github.com/node-geojson/geojson-flatten), a module that you can use to 'flatten' such complex forms into flat forms, that can be used as a preprocessing step for applications that support a subset of GeoJSON, like gl-js and the features API. That module or an equivalent is already used in spots where people upload GeoJSON to Mapbox, like Mapbox Studio.

KML supports GeometryCollections, GeoJSON supports them too. A tool that converts from KML to GeoJSON should turn GeometryCollections in KML to the same construct in GeoJSON.

**Comment by bhousel** [comment]
> The attached vectors.zip file contains a correct GeoJSON file, that passes geojsonhint except for the winding rule, which is a warning, not an error.

Ah gotcha - this was the part I was missing.  @samsammurphy said it was an "illegal FeatureCollection" and I assumed `toGeoJSON` was producing invalid output.

Since the utility is working as expected, and the issues are with other software, I agree that this issue should be closed.

**Comment by alexyuly** [comment]
@tmcw
Thanks for the explanation, and I agree. And thank you for the link to geojson-flatten, as it looks like that fits my use case perfectly and solves my problem.
