### ISSUE TITLE
Firebase Functions: Error parsing triggers: Cannot find module 'togeojson'

### ISSUE THREAD

**Issue by arpitgoyal2008** [mapbox/togeojson#148]
I am trying to use @mapbox/togeojson with Firebase Functions. But, while doing firebase deploy in project root Dir, I am getting

`Error: Error parsing triggers: Cannot find module 'togeojson'
Try running "npm install" in your functions directory before deploying.`

I have run npm install multiple times from functions/ folder. Following is my content for package.json

`{
  "name": "functions",
  "description": "Cloud Functions for Firebase",
  "scripts": {
     "lint": "eslint .",
     "serve": "firebase serve --only functions",
     "shell": "firebase functions:shell",
     "start": "npm run shell",
     "deploy": "firebase deploy --only functions",
     "logs": "firebase functions:log"
  },
  "dependencies": {
     "@google-cloud/storage": "^0.4.0",
     "@mapbox/togeojson": "^0.16.0",
     "brfs": "^2.0.0",
     "coveralls": "^3.0.2",
     "cz-conventional-changelog": "^2.1.0",
     "firebase-admin": "~6.0.0",
     "firebase-functions": "^2.0.3",
     "glob": "^7.1.2",
     "istanbul": "^0.4.5",
     "mkdirp": "^0.5.1",
     "mkdirp-promise": "^4.0.0",
     "tape": "^4.9.1"
  },
  "devDependencies": {
    "eslint": "^4.19.1",
    "eslint-plugin-promise": "^3.6.0"
 },
 "private": true 
}`
Kindly help

**Comment by ykorach** [comment]
Hi seems like I have similar issue.
Why did you close it? did you find any solution?

**Comment by arpitbidgely** [comment]
Hey,
Are you using this to import python module

`var tj = require('@mapbox/togeojson');`
This solved my issue
