### ISSUE TITLE
Minimist dependency is causing Moderate-level security issue when running npm audit

### ISSUE THREAD

**Issue by mjcella** [mapbox/togeojson#163]
The togeojson package has minimist as one of its dependencies. Minimist recently had a security vulnerability reported with NPM. Running npm audit on a project with togeojson installed returns the following:

| Moderate      | Prototype Pollution                     |
|---------------|-----------------------------------------|
| Package       | minimist                                |
| Patched in    | &gt;=0.2.1 &lt; 1.0.0  or &gt;=1.2.3                          |
| Dependency of | claudia-local-api                       |
| Path          | claudia-local-api > bunyan > mv > mkdirp > minimist            |
| More info     | https://nodesecurity.io/advisories/1179 |

**Comment by mrinc** [comment]
I've done an update, but it was never merged: https://github.com/mapbox/togeojson/pull/171  

I've just pushed a new package off my repo with all the dep updates: https://github.com/mrinc/togeojson/tree/mrinc/togeojson  
https://www.npmjs.com/package/@mrinc/togeojson
