### ISSUE TITLE
invalid output for GPX-routes

### ISSUE THREAD

**Issue by tyrasd** [mapbox/togeojson#59]
When converting a GPX file containing a [route](http://www.topografix.com/GPX/1/1/#type_rteType), the resulting GeoJSON output is faulty, containing an invalid `coordinates` object. See this [example gist](https://gist.github.com/tyrasd/8c8cd94b5f3db394550a). This is a regression between v0.9 and v0.10.

**Comment by tmcw** [comment]
Fixed in #67
