### ISSUE TITLE
Parse the "folder" tag

### ISSUE THREAD

**Issue by yccteam** [mapbox/togeojson#64]
Hi, first of all, you have my thanks for a very nice parser.
Now for the issue: the ```folder ``` tag divides the data into meaningful groups/layers. I could not see that toGeoJson handles it - it seems to be ignored. Am I missing something?

**Comment by tmcw** [comment]
I don't think that GeoJSON has a way to express folders, or most other formats for that matter.

**Comment by yccteam** [comment]
I believe "GeometryCollection" would be the equivalent, wouldn't you agree? 
I've started implementing this, but since I'm new to geoJson and KML, it might take a while.
My direction is to look for a ```folder``` element, and if exists, take its placemarks and put them in a ```GeometryCollection``` in a geoJson.
If it doesn't exist, parse as usual.
Another case might be that there are folders, but also "root" ```placemarks```, and for this case, I should also search for ```placemarks``` that are not inside a ```folder```.
Do you believe this to be the right direction?
Do you have any contribution guidelines? I'll be happy to share my code.

**Comment by tmcw** [comment]
> I believe "GeometryCollection" would be the equivalent, wouldn't you agree? 

GeometryCollection is a collection of Geometries. Folders are collections of Placemarks, other folders, and more. Unfortunately they aren't equivalents

**Comment by yccteam** [comment]
Hmmm... I see what you mean. So it would seem that a ```Placemark``` can hold several Geometries.  It seems that my case is not a general one...  thanks for the clarification :)

**Comment by SuberFu** [comment]
Perhaps a capability to have an option to return a collection of layers? One for each folder?

**Comment by tmcw** [comment]
GeoJSON does not have a construct for a "collection of layers": toGeoJSON must return valid GeoJSON, and the GeoJSON format does not have an equivalent construct for this part of KML.

**Comment by tmcw** [comment]
Closing; there is no equivalent concept, so there will be no conversion.

**Comment by dtruel** [comment]
Well, this is kind of a bummer... Does anybody have any ideas for workarounds?

**Comment by FBrusquetti** [comment]
I forket the repo and added an temporal solution, my solution add a new property to the geometry with the folder name, see: https://github.com/FBrusquetti/togeojson/commit/4219d384d80cbf4b7fe743c482e0ac54990f5bef

**Comment by dtruel** [comment]
@FBrusquetti looks cool!  I ended up just writing a custom KML parser myself... Turns out it's not actually that hard.
