### ISSUE TITLE
option to remove the elevation

### ISSUE THREAD

**Issue by franckl** [mapbox/togeojson#66]
Would it be possible to remove the elevation from the converted geojson with an option ?

**Comment by tmcw** [comment]
Hm, it's possible. Might I ask why you want to remove it?

**Comment by franckl** [comment]
It would be really nice ! it causes an issue with mongoDB : 
 "insertDocument :: caused by :: 16755 Can't extract geo keys from object, malformed geometry?

**Comment by franckl** [comment]
specifically http://docs.mongodb.org/manual/core/2dsphere/

**Comment by tmcw** [comment]
That's a bug in Mongo.

**Comment by franckl** [comment]
It's in the specs http://docs.mongodb.org/manual/reference/glossary/#term-legacy-coordinate-pairs
I will submit a report to mongodb but it will take ages

**Comment by tmcw** [comment]
You can solve this problem outside of toGeoJSON:

    npm install turf-meta

and

```js
var meta = require('turf-meta');
meta.coordEach(geojson, function(coords) {
   if (coords.length > 2) coords.pop();
});
```

with https://github.com/turfjs/turf-meta

---

not going to add code to togeojson to avoid a bug in mongo: mongo should fix their bugs.
