### ISSUE TITLE
Syncing times and coordinates

### ISSUE THREAD

**Issue by jonalling** [mapbox/togeojson#83]
Is it possible to synchronize the coordTimes and coordinates when converting GPX to geoJSON?  Your browser based tool seems to strip the times completely, and the command line implementation separates the coordinates (in geometry) from the coordTimes (in properties).

**Comment by tmcw** [comment]
> the command line implementation separates the coordinates (in geometry) from the coordTimes (in properties)

This is by design: putting time values in coordinates in GeoJSON is not specified and probably a dangerous idea. See https://github.com/mapbox/geojson-coordinate-properties for the draft spec.

**Comment by jonalling** [comment]
OK, thanks.  The data is still keyed so I can extract a time/coordinate pair correct?

**Comment by tmcw** [comment]
Yes, the coordinates array and properties arrays are symmetrical.
