### ISSUE TITLE
Better handling of invalid coordinate values

### ISSUE THREAD

**Issue by daredevil82** [mapbox/togeojson#89]
In https://github.com/Leaflet/Leaflet/issues/3424, @hs06 reported that when importing a KML via leaflet-omnivore with an empty coordinate array, Leaflet crashes.  I've also duplicated this issue with a KML which returns a `[NaN]` array.  You should be able to duplicate this via the file below, as it is a KMZ renamed to ZIP to conform to Github's attachment file type restrictions.
[Portland Trails Presumpscot River Preserve.zip](https://github.com/mapbox/togeojson/files/87170/Portland.Trails.Presumpscot.River.Preserve.zip)

This code snippet reads in a KML string from a file and fits the map view to the bounds of the paths:

        leafletData.getMap('map-preview').then(function(map) {
            var kml = fileReader.getLocalFile();  //Angular service to store text read from file

            if (kml === null)
                $log.error("No file loaded");
            else {
               //transform KML string to DOM object and parse
                var kmlDom = (new DOMParser()).parseFromString(fileReader.getLocalFile(), 'text/xml');
                var pathData = toGeoJSON.kml(kmlDom);

                angular.extend($scope,  {
                    geojson : {
                        data : pathData,
                        style : {
                            dashArray : '3',
                            color : 'black',
                            weight : 8
                        }
                    }
                });

                var latlng = [];
                
                //iterate over GeoJSON features to create an array of all coordinates in data set
                for (var feature in pathData.features) {
                    var paths = pathData.features[feature].geometry.coordinates;
                    paths = _.compact(paths);

                    for (var path in paths) {
                        var prospectiveCoords = pathData.features[feature].geometry.coordinates[path];
                        var coordinate = L.GeoJSON.coordsToLatLng(prospectiveCoords);
                        //$log.debug(coordinate);
                        latlng.push(coordinate);
                    }
                }

                map.fitBounds(latlng);

                //Use parsed GeoJSON data to add a layer to the map.  
                //Cause of Error: Invalid LatLng object: (NaN, NaN) in Leaflet.
                L.geoJson(pathData, {
                    style : {
                        color : 'black',
                        weight : 10
                    }
                }).addTo(map);
            }
        });

I can see two possible solutions to this:

1. Throw a verbose error when encountering an invalid numerical value when building coordinate arrays
2. If any invalid or NaN value is found during processing, remove that coordinate array from the parsed results and display a verbose error

**Comment by tmcw** [comment]
I'm inclined to keep the behavior as-is. toGeoJSON is a KML converter, not a KML validator, and it should not be any more tolerant of incorrect data than it must be.

**Comment by daredevil82** [comment]
Agreed, but raising an exception when invalid data is encountered is good practice, and the developer can then decide whether to act upon said error or ignore it.  Currently there is no way to make this choice.

**Comment by tmcw** [comment]
Parsers do not always throw when invalid data is encountered; they throw when the source data is incorrect in a way that breaks the parser. Throwing whenever 'invalid data is encountered' necessitates building a KML validator - anything else will be fixing this narrow case you found, and letting the infinite other invalid potentials pass through, such that toGeoJSON will be a validating parser for one particular, relatively rare, issue.

Closing; please use a KML validator if you want to ensure that your data is valid.
