### ISSUE TITLE
GPX waypoint support please

### ISSUE THREAD

**Issue by gertcuykens** [mapbox/togeojson#90]
```xml
 <wpt lat="52.069078702479601" lon="5.176963554695249">
    <time>2015-11-19T16:03:10Z</time>
    <name>CP-00 Start StayOkay</name>
    <cmt>Bunnik</cmt>
    <desc>Bunnik</desc>
    <sym>Flag, Red</sym>
    <extensions>
      <gpxx:WaypointExtension xmlns:gpxx="http://www.garmin.com/xmlschemas/GpxExtensions/v3">
        <gpxx:DisplayMode>SymbolAndName</gpxx:DisplayMode>
      </gpxx:WaypointExtension>
    </extensions>
  </wpt>
```
[example BRM200BNK-16-500.gpx.zip](https://github.com/mapbox/togeojson/files/102108/BRM200BNK-16-500.gpx.zip)

**Comment by tmcw** [comment]
@gertcuykens I tested this example and it converts. Are you looking for some particular part to be converted differently?

**Comment by gertcuykens** [comment]
It converts but are the waypoints still in the json file or just the track? Let me take a closer look at the json output first because I was convinced it didn't create separate geo points representing the way points only the track polygon when I checked the json file with mapbox studio and compared it with the gpx in studio.

**Comment by gertcuykens** [comment]
You are right lol :) they are at the bottom, hmm why does mapbox studio discard them?
