### ISSUE TITLE
Shouldn't relations in OSM be mapped to MultilineStrings in geojson instead of separate LineStrings?

### ISSUE THREAD

**Issue by HarelM** [mapbox/togeojson#96]
I'm trying to covert a response from overpass to geojson and I want to know the bounding box of a relation. In current conversion I need to iterate on all features and group them by relation before I can do it... :-/

**Comment by tmcw** [comment]
toGeoJSON converts from KML or GPX, not from OSM data - this is not the correct issue tracker for this question.

**Comment by HarelM** [comment]
Sorry, my bad.
