### ISSUE TITLE
Ignoring icon url in style

### ISSUE THREAD

**Issue by dorelm** [mapbox/togeojson#98]
When I input a kml with an Iconstyle in an inline style element it is ignored.

**Comment by tmcw** [comment]
Hi @dorelm!

Yep, you're right to notice that icon images aren't reflected in generated GeoJSON. This is the first report we've had of this bug/feature request. If you'd like to fix it, I'd love to accept a Pull Request. If not, I'll keep this issue for anyone else who has the time & motivation to make this change.

Thanks!

Tom
